/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as ApiPublicHooksRutinaDiariaRouteImport } from './routes/api/public/hooks/rutina-diaria'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/_authenticated/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRutinaDiariaRoute =
  ApiPublicHooksRutinaDiariaRouteImport.update({
    id: '/api/public/hooks/rutina-diaria',
    path: '/api/public/hooks/rutina-diaria',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
}
export interface FileRoutesByTo {
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/colaboradores' | '/' | '/api/public/hooks/rutina-diaria'
  fileRoutesByTo: FileRoutesByTo
  to: '/colaboradores' | '/' | '/api/public/hooks/rutina-diaria'
  id:
    | '__root__'
    | '/_authenticated/colaboradores'
    | '/_authenticated/'
    | '/api/public/hooks/rutina-diaria'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  ApiPublicHooksRutinaDiariaRoute: typeof ApiPublicHooksRutinaDiariaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rutina-diaria': {
      id: '/api/public/hooks/rutina-diaria'
      path: '/api/public/hooks/rutina-diaria'
      fullPath: '/api/public/hooks/rutina-diaria'
      preLoaderRoute: typeof ApiPublicHooksRutinaDiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  ApiPublicHooksRutinaDiariaRoute: ApiPublicHooksRutinaDiariaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
