/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DataDeletionRouteImport } from './routes/data-deletion'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedBorradoresRouteImport } from './routes/_authenticated/borradores'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedConexionesRouteImport } from './routes/_authenticated/conexiones'
import { Route as AuthenticatedContenidoRouteImport } from './routes/_authenticated/contenido'
import { Route as AuthenticatedCredencialesRouteImport } from './routes/_authenticated/credenciales'
import { Route as AuthenticatedMensajeriaRouteImport } from './routes/_authenticated/mensajeria'
import { Route as AuthenticatedProgramacionRouteImport } from './routes/_authenticated/programacion'
import { Route as ApiPublicHooksPublicarProgramadoRouteImport } from './routes/api/public/hooks/publicar-programado'
import { Route as ApiPublicHooksRutinaDiariaRouteImport } from './routes/api/public/hooks/rutina-diaria'
import { Route as ApiPublicOauthMetaCallbackRouteImport } from './routes/api/public/oauth/meta/callback'
import { Route as ApiPublicOauthTiktokCallbackRouteImport } from './routes/api/public/oauth/tiktok/callback'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DataDeletionRoute = DataDeletionRouteImport.update({
  id: '/data-deletion',
  path: '/data-deletion',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBorradoresRoute = AuthenticatedBorradoresRouteImport.update({
  id: '/borradores',
  path: '/borradores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConexionesRoute = AuthenticatedConexionesRouteImport.update({
  id: '/conexiones',
  path: '/conexiones',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContenidoRoute = AuthenticatedContenidoRouteImport.update({
  id: '/contenido',
  path: '/contenido',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCredencialesRoute =
  AuthenticatedCredencialesRouteImport.update({
    id: '/credenciales',
    path: '/credenciales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMensajeriaRoute = AuthenticatedMensajeriaRouteImport.update({
  id: '/mensajeria',
  path: '/mensajeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProgramacionRoute =
  AuthenticatedProgramacionRouteImport.update({
    id: '/programacion',
    path: '/programacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksPublicarProgramadoRoute =
  ApiPublicHooksPublicarProgramadoRouteImport.update({
    id: '/api/public/hooks/publicar-programado',
    path: '/api/public/hooks/publicar-programado',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksRutinaDiariaRoute =
  ApiPublicHooksRutinaDiariaRouteImport.update({
    id: '/api/public/hooks/rutina-diaria',
    path: '/api/public/hooks/rutina-diaria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthMetaCallbackRoute =
  ApiPublicOauthMetaCallbackRouteImport.update({
    id: '/api/public/oauth/meta/callback',
    path: '/api/public/oauth/meta/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicOauthTiktokCallbackRoute =
  ApiPublicOauthTiktokCallbackRouteImport.update({
    id: '/api/public/oauth/tiktok/callback',
    path: '/api/public/oauth/tiktok/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/borradores': typeof AuthenticatedBorradoresRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/conexiones': typeof AuthenticatedConexionesRoute
  '/contenido': typeof AuthenticatedContenidoRoute
  '/credenciales': typeof AuthenticatedCredencialesRoute
  '/mensajeria': typeof AuthenticatedMensajeriaRoute
  '/programacion': typeof AuthenticatedProgramacionRoute
  '/api/public/hooks/publicar-programado': typeof ApiPublicHooksPublicarProgramadoRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/borradores': typeof AuthenticatedBorradoresRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/conexiones': typeof AuthenticatedConexionesRoute
  '/contenido': typeof AuthenticatedContenidoRoute
  '/credenciales': typeof AuthenticatedCredencialesRoute
  '/mensajeria': typeof AuthenticatedMensajeriaRoute
  '/programacion': typeof AuthenticatedProgramacionRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/publicar-programado': typeof ApiPublicHooksPublicarProgramadoRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/data-deletion': typeof DataDeletionRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/borradores': typeof AuthenticatedBorradoresRoute
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/conexiones': typeof AuthenticatedConexionesRoute
  '/_authenticated/contenido': typeof AuthenticatedContenidoRoute
  '/_authenticated/credenciales': typeof AuthenticatedCredencialesRoute
  '/_authenticated/mensajeria': typeof AuthenticatedMensajeriaRoute
  '/_authenticated/programacion': typeof AuthenticatedProgramacionRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/hooks/publicar-programado': typeof ApiPublicHooksPublicarProgramadoRoute
  '/api/public/hooks/rutina-diaria': typeof ApiPublicHooksRutinaDiariaRoute
  '/api/public/oauth/meta/callback': typeof ApiPublicOauthMetaCallbackRoute
  '/api/public/oauth/tiktok/callback': typeof ApiPublicOauthTiktokCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/borradores'
    | '/colaboradores'
    | '/conexiones'
    | '/contenido'
    | '/credenciales'
    | '/mensajeria'
    | '/programacion'
    | '/api/public/hooks/publicar-programado'
    | '/api/public/hooks/rutina-diaria'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/tiktok/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/borradores'
    | '/colaboradores'
    | '/conexiones'
    | '/contenido'
    | '/credenciales'
    | '/mensajeria'
    | '/programacion'
    | '/'
    | '/api/public/hooks/publicar-programado'
    | '/api/public/hooks/rutina-diaria'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/tiktok/callback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/data-deletion'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/borradores'
    | '/_authenticated/colaboradores'
    | '/_authenticated/conexiones'
    | '/_authenticated/contenido'
    | '/_authenticated/credenciales'
    | '/_authenticated/mensajeria'
    | '/_authenticated/programacion'
    | '/_authenticated/'
    | '/api/public/hooks/publicar-programado'
    | '/api/public/hooks/rutina-diaria'
    | '/api/public/oauth/meta/callback'
    | '/api/public/oauth/tiktok/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DataDeletionRoute: typeof DataDeletionRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ApiPublicHooksPublicarProgramadoRoute: typeof ApiPublicHooksPublicarProgramadoRoute
  ApiPublicHooksRutinaDiariaRoute: typeof ApiPublicHooksRutinaDiariaRoute
  ApiPublicOauthMetaCallbackRoute: typeof ApiPublicOauthMetaCallbackRoute
  ApiPublicOauthTiktokCallbackRoute: typeof ApiPublicOauthTiktokCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-deletion': {
      id: '/data-deletion'
      path: '/data-deletion'
      fullPath: '/data-deletion'
      preLoaderRoute: typeof DataDeletionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/borradores': {
      id: '/_authenticated/borradores'
      path: '/borradores'
      fullPath: '/borradores'
      preLoaderRoute: typeof AuthenticatedBorradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conexiones': {
      id: '/_authenticated/conexiones'
      path: '/conexiones'
      fullPath: '/conexiones'
      preLoaderRoute: typeof AuthenticatedConexionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contenido': {
      id: '/_authenticated/contenido'
      path: '/contenido'
      fullPath: '/contenido'
      preLoaderRoute: typeof AuthenticatedContenidoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/credenciales': {
      id: '/_authenticated/credenciales'
      path: '/credenciales'
      fullPath: '/credenciales'
      preLoaderRoute: typeof AuthenticatedCredencialesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mensajeria': {
      id: '/_authenticated/mensajeria'
      path: '/mensajeria'
      fullPath: '/mensajeria'
      preLoaderRoute: typeof AuthenticatedMensajeriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/programacion': {
      id: '/_authenticated/programacion'
      path: '/programacion'
      fullPath: '/programacion'
      preLoaderRoute: typeof AuthenticatedProgramacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/publicar-programado': {
      id: '/api/public/hooks/publicar-programado'
      path: '/api/public/hooks/publicar-programado'
      fullPath: '/api/public/hooks/publicar-programado'
      preLoaderRoute: typeof ApiPublicHooksPublicarProgramadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rutina-diaria': {
      id: '/api/public/hooks/rutina-diaria'
      path: '/api/public/hooks/rutina-diaria'
      fullPath: '/api/public/hooks/rutina-diaria'
      preLoaderRoute: typeof ApiPublicHooksRutinaDiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/meta/callback': {
      id: '/api/public/oauth/meta/callback'
      path: '/api/public/oauth/meta/callback'
      fullPath: '/api/public/oauth/meta/callback'
      preLoaderRoute: typeof ApiPublicOauthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/oauth/tiktok/callback': {
      id: '/api/public/oauth/tiktok/callback'
      path: '/api/public/oauth/tiktok/callback'
      fullPath: '/api/public/oauth/tiktok/callback'
      preLoaderRoute: typeof ApiPublicOauthTiktokCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBorradoresRoute: typeof AuthenticatedBorradoresRoute
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConexionesRoute: typeof AuthenticatedConexionesRoute
  AuthenticatedContenidoRoute: typeof AuthenticatedContenidoRoute
  AuthenticatedCredencialesRoute: typeof AuthenticatedCredencialesRoute
  AuthenticatedMensajeriaRoute: typeof AuthenticatedMensajeriaRoute
  AuthenticatedProgramacionRoute: typeof AuthenticatedProgramacionRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBorradoresRoute: AuthenticatedBorradoresRoute,
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConexionesRoute: AuthenticatedConexionesRoute,
  AuthenticatedContenidoRoute: AuthenticatedContenidoRoute,
  AuthenticatedCredencialesRoute: AuthenticatedCredencialesRoute,
  AuthenticatedMensajeriaRoute: AuthenticatedMensajeriaRoute,
  AuthenticatedProgramacionRoute: AuthenticatedProgramacionRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DataDeletionRoute: DataDeletionRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ApiPublicHooksPublicarProgramadoRoute: ApiPublicHooksPublicarProgramadoRoute,
  ApiPublicHooksRutinaDiariaRoute: ApiPublicHooksRutinaDiariaRoute,
  ApiPublicOauthMetaCallbackRoute: ApiPublicOauthMetaCallbackRoute,
  ApiPublicOauthTiktokCallbackRoute: ApiPublicOauthTiktokCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
